### ISSUE TITLE
Kreditering af fotografer i galleri-funktion

### ISSUE THREAD

**Issue by BueHeckmann** [sl2017/spejderneslejrdk#113]
-	Hvordan tilføjer jeg fotograf kredit på forsidens galleri? – måske via galleri reference, men kan ikke lige lure hvorledes den virker. Se hvad jeg gerne vil kunne her https://web.archive.org/web/20161015070545/http://spejderneslejr.dk/da

**Comment by danquah** [comment]
@BueHeckmann du lave en simpel forside, tilføjer en "Frontpage gallery" paragraf, tilføjet et billede, trykker redigér på billedet, og udfylder krediteringen under "credit".

Det skal siges jeg ikke har testet det, så sig til hvis du allerede har prøvet der der eller det ikke lige giver mening så får jeg lige prøvet det helt af selv :)

**Comment by BueHeckmann** [comment]
Heh, det virker :)
